import pygame
FRAMERATE = 120
SCREEN_HEIGHT = 600
SCREEN_WIDTH = 1200
MOVE_SPD = 5
BOTTOM_BORD = 200
JUMP_TIMEOUT = 100
WORLD_SPEED = 4
screen = pygame.display.set_mode((SCREEN_WIDTH, SCREEN_HEIGHT))
